### ISSUE TITLE
Don't save different capitalizations in array.

### ISSUE THREAD

**Issue by tomrayner1** [EthanHoward/JMC#1]
https://github.com/EthanHoward/JMC/blob/e45cc50d2a4fcd2c41e7da90e0809f1b28b0b61f/jmc.py#L5
https://github.com/EthanHoward/JMC/blob/e45cc50d2a4fcd2c41e7da90e0809f1b28b0b61f/jmc.py#L6
I know this isn't used in the file however you should only save lowercase versions in the array.
You can then compare strings with the lowercase version.
Look at String.lower() or String.casefold().

[Shoutout to stackoverflow.](https://stackoverflow.com/questions/319426/how-do-i-do-a-case-insensitive-string-comparison)

**Comment by EthanHoward** [comment]
Removed them anyways, I would’ve probably thought of that if I’d actually used it but i didnt, thanks for sharpening my eye on that code though
